# Generated by Django 3.1.3 on 2020-11-11 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0001_initial'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='analyse.profil'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chat',
            name='user_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='analyse.profil'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='user_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyse.profil'),
        ),
    ]
