# Generated by Django 3.1.3 on 2020-11-12 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20201111_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='last_message',
            field=models.ForeignKey(default=92, on_delete=django.db.models.deletion.CASCADE, related_name='last_message', to='chat.message'),
            preserve_default=False,
        ),
    ]
