# Generated by Django 3.1.3 on 2020-11-15 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chat_last_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='last_message',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_message', to='chat.message'),
        ),
    ]
