# Generated by Django 3.1.3 on 2020-11-15 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20201115_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='timestamp',
        ),
    ]
